apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "{{ .Chart.name }}"
    http:
      paths:
      - path: /
        backend:
            serviceName: client-service
            servicePort: {{ .Values.client.service.port }}
