apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.parser.serviceName}}-deployment"
spec:
  replicas: {{ .Values.parser.replicaCount }}
  selector:
    matchLabels:
      component: {{.Values.parser.serviceName}}
  template:
    metadata:
      labels:
        component: {{.Values.parser.serviceName}}
    spec:
        containers:
          - name: "{{ .Values.app.image.appName }}-{{.Values.parser.serviceName}}"
            image: "{{ .Values.app.image.repository }}/{{ .Values.app.image.appName }}-{{.Values.parser.serviceName}}:{{ .Values.parser.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.app.image.pullPolicy }}
            ports:
              - name: http
                containerPort: {{ .Values.parser.service.port }}
                protocol: TCP
            env:
              - name: PORT
                valueFrom:
                  configMapKeyRef:
                    name: env
                    key: PARSER_PORT
