apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.parser.serviceName}}-service"
spec:
  type: {{ .Values.parser.service.type }}
  ports:
    - port: {{ .Values.parser.service.port }}
      targetPort: {{ .Values.parser.service.port }}
      protocol: TCP
  selector:
    component: {{.Values.parser.serviceName}}
