apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.server.serviceName}}-service"
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
  selector:
    component: {{.Values.server.serviceName}}
