apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.worker.serviceName}}-service"
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: {{ .Values.worker.service.port }}
      protocol: TCP
  selector:
    component: {{.Values.worker.serviceName}}
